### ISSUE TITLE
عمومی نشد

### ISSUE THREAD

**Issue by hadiwwe** [sajjadsoleimani/qroz_rubika_bot#2]
سلام
اگه در یک جلسه بدون مقدمه چینی و... بدون نیاز به اینکه پایتون بلد باشی آموزش ساخت ب*ات روبیکا رو می ذاشتی خیلی بهتر بود 🤷‍♂️

**Comment by kinite-GP** [comment]
اگه اون پایین ببینی ربات 100 درصد با پایتونه
بدون نیاز به پایتون 
میتونی کد کروز رو کپی کنی تو یه فایل پایتون جدید
